server:
   port: 80

spring:
  application:
    name: cloud-consumer-openfeign-order

eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/


ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000

logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug