server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh1
          uri: http://localhost:8001
          predicate:
            - path=/payment/get/**

        - id: payment_routh2
            uri: http://localhost:8001
            predicate:
              - path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://eureka7001.com:7001/eureka/